sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t shashank0490/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shashank0490/docker-react npm run test

